version: "3"
services:
  java:
    image: ghcr.io/bertrik/ttn-gateway-collector
    build: ..
    restart: always
    volumes:
      - "./ttn-gateway-collector.yaml:/opt/ttn-gateway-collector/ttn-gateway-collector.yaml:ro"
      - "./log4j.properties:/opt/ttn-gateway-collector/log4j.properties:ro"
      - "./log:/opt/ttn-gateway-collector/log:rw"
      - "./gateway.csv:/opt/ttn-gateway-collector/gateway.csv:rw"

